# Generated by Django 2.2.8 on 2020-06-01 16:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCDSReleaseJSON',
            fields=[
                ('ocid', models.TextField(primary_key=True, serialize=False)),
                ('release_id', models.TextField()),
                ('release_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'db_table': 'bluetail_ocds_release_json',
            },
        ),
    ]
