# Generated by Django 2.2.10 on 2020-06-10 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bluetail', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX ON public.bluetail_bods_statement_json ((statement_json ->> 'statementType'))"
        )
    ]
