# Generated by Django 2.2.10 on 2020-06-10 21:34
"""
This migration is created manually to speed up lookups in bluetail_bods_statement_json.
There are Django packages that support an integrated migration generation for specific SQL

https://github.com/yjmade/django-pgjsonb
https://github.com/festicket/django-migrate-sql
"""

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bluetail', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX ON public.bluetail_bods_statement_json ((statement_json ->> 'statementType'))"
        )
    ]
