# Generated by Django 2.2.13 on 2020-07-06 08:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0008_supplieddata_data_schema_version'),
        ('bluetail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCDSPackageDataJSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('supplied_data', models.ForeignKey(null=True, on_delete=None, to='input.SuppliedData')),
            ],
            options={
                'db_table': 'bluetail_ocds_package_data_json',
            },
        ),
        migrations.AddField(
            model_name='ocdsreleasejson',
            name='package_data',
            field=models.ForeignKey(null=True, on_delete=None, to='bluetail.OCDSPackageDataJSON'),
        ),
    ]
