# Generated by Django 2.2.8 on 2020-06-01 16:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluetail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCDSReleaseView',
            fields=[
                ('ocid', models.TextField(primary_key=True, serialize=False)),
                ('release_id', models.TextField()),
                ('release_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'bluetail_ocds_release_view',
                'managed': False,
            },
        ),
    ]
