# Generated by Django 2.2.8 on 2020-06-01 18:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluetail', '0002_ocdsreleaseview'),
    ]

    operations = [
        migrations.CreateModel(
            name='BODSEntityStatementJSON',
            fields=[
                ('statement_id', models.TextField(primary_key=True, serialize=False)),
                ('statement_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'db_table': 'bluetail_bods_entitystatement_json',
            },
        ),
        migrations.CreateModel(
            name='BODSOwnershipStatementJSON',
            fields=[
                ('statement_id', models.TextField(primary_key=True, serialize=False)),
                ('statement_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'db_table': 'bluetail_bods_ownershipstatement_json',
            },
        ),
        migrations.CreateModel(
            name='BODSPersonStatementJSON',
            fields=[
                ('statement_id', models.TextField(primary_key=True, serialize=False)),
                ('statement_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'db_table': 'bluetail_bods_personstatement_json',
            },
        ),
    ]
