# Generated by Django 2.2.13 on 2020-07-06 10:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluetail', '0002_auto_20200706_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCDSPackageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('uri', models.TextField()),
                ('publishedDate', models.DateTimeField()),
                ('publisher', django.contrib.postgres.fields.jsonb.JSONField()),
                ('publisher_uid', models.TextField()),
                ('publisher_uri', models.TextField()),
                ('publisher_name', models.TextField()),
                ('publisher_scheme', models.TextField()),
                ('extensions', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'bluetail_ocds_package_data_view',
                'managed': False,
            },
        ),
    ]
