# Generated by Django 2.2.13 on 2020-07-08 08:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluetail', '0003_ocdspackagedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCDSRecordJSON',
            fields=[
                ('ocid', models.TextField(primary_key=True, serialize=False)),
                ('record_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('package_data', models.ForeignKey(null=True, on_delete=None, to='bluetail.OCDSPackageDataJSON')),
            ],
            options={
                'db_table': 'bluetail_ocds_record_json',
            },
        ),
    ]
