# Generated by Django 2.2.13 on 2020-07-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluetail', '0004_ocdsrecordjson'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=1024)),
                ('name', models.CharField(max_length=1024)),
                ('identifier', models.CharField(max_length=1024)),
                ('date_of_birth', models.DateField(null=True)),
                ('flag', models.ForeignKey(on_delete=None, to='bluetail.Flag')),
            ],
        ),
        migrations.AddConstraint(
            model_name='externalperson',
            constraint=models.UniqueConstraint(fields=('name', 'scheme', 'identifier', 'flag'), name='unique_person_flag'),
        ),
    ]
