# Generated by Django 2.2.13 on 2020-07-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherMetrics',
            fields=[
                ('publisher_id', models.TextField(primary_key=True, serialize=False)),
                ('publisher_name', models.TextField(null=True)),
                ('count_lastmonth', models.IntegerField(null=True)),
                ('count_last3months', models.IntegerField(null=True)),
                ('count_last12months', models.IntegerField(null=True)),
                ('average_lastmonth', models.IntegerField(null=True)),
                ('average_last3months', models.IntegerField(null=True)),
                ('average_last12months', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'silvereye_publisher_metrics',
            },
        ),
    ]
