#!/bin/bash

# abort on any errors
set -e

 check that we are in the expected directory
cd `dirname $0`/..

# make sure that there is no old code (the .py files may have been git deleted)
find . -name '*.pyc' -delete

# Build venv using pipenv
pipenv install --deploy