#!/bin/sh

set -e

# Move to top level of project.
cd `dirname $0`/..

find . -name '*.pyc' -delete

# Recreate database.
sudo -u postgres psql -c "DROP DATABASE IF EXISTS bluetail"
sudo -u postgres psql -c "CREATE DATABASE bluetail"

# Create database user if not exists.
sudo -u postgres psql -c "SELECT 'exists' FROM pg_roles WHERE rolname='bluetail'" | grep -q 'exists' || sudo -u postgres psql -c "CREATE USER bluetail SUPERUSER CREATEDB PASSWORD 'bluetail'"

# Set up database.
script/migrate

# Insert example data.
script/insert_example_data

# Create superuser.
script/console -c "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'admin@example.com', 'admin')"
