#!/bin/sh

sudo apt-get update

#upgrade local python3 to python3.6
cd /vagrant
sudo apt-get install -y libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm
sudo apt-get install -y libncurses5-dev  libncursesw5-dev xz-utils tk-dev libssl-dev

sudo wget https://www.python.org/ftp/python/3.6.6/Python-3.6.6.tgz
sudo tar xvf Python-3.6.6.tgz
cd Python-3.6.6
sudo ./configure --enable-optimizations --with-ssl=openssl
sudo make -j8
sudo make altinstall
sudo update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.6 1
sudo rm /usr/bin/lsb_release

cd /vagrant/bluetail

#fix dpkg-preconfigure error
export DEBIAN_FRONTEND=noninteractive

# Install the packages from conf/packages
xargs sudo apt-get install -qq -y < conf/packages
xargs sudo apt-get install -qq -y < conf/dev_packages
# Install some of the other things we need that are just for dev
sudo apt-get install -qq -y ruby-dev libsqlite3-dev build-essential

# Create postgres database and user.
sudo -u postgres psql -c "CREATE DATABASE bluetail"
sudo -u postgres psql -c "CREATE USER bluetail SUPERUSER CREATEDB PASSWORD 'bluetail'"

# Set up Python packages in a virtualenv
script/bootstrap

# Give permissions to vagrant user on all the packages
sudo chmod -R ugo+rwx /vagrant/venv

if ! grep "SECRET_KEY=" /home/vagrant/.bashrc ; then
    echo "export SECRET_KEY=\"$SECRET_KEY\"" >> /home/vagrant/.bashrc
fi

if ! grep "DATABASE_URL=" /home/vagrant/.bashrc ; then
    echo "export DATABASE_URL=\"$DATABASE_URL\"" >> /home/vagrant/.bashrc
fi

# Run migrations, insert example data, etc.
script/setup
